services:
  web:
      container_name: "Gym_V2_Frontend"
      build: ./frontend
      ports: 
        - 3000:3000
      # env_file: "./frontend/.env.local" # for next js
      develop:
        watch:
          - path: ./package.json
            action: rebuild
          - path: ./package.lock.json
            action: rebuild
          - path: ./frontend
            target: /app
            action: sync
      
      depends_on:
        - api
  
  api:
    container_name: "Gym_V2_Backend"
    build: ./backend
    ports:
      - 8000:8000
    env_file: "./backend/.env"

    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis

    develop:
        watch:
          - path: ./requirements.txt
            action: rebuild
          - path: ./backend
            target: /app
            action: sync

    depends_on:
      - db
      - redis
    
  db:
    container_name: "Gym_V2_db"
    image: postgres:latest
    env_file: "./backend/.env"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: "Gym_V2_Redis"
    image: redis/redis-stack:latest
    env_file: "./backend/.env"
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
    name: "Gym_V2_Postgres_Volume"
  redis_data:
    name: "Gym_V2_Redis_Volume"